### ISSUE TITLE
test_dsLasso.R - Lexical error at line 755, column 60

### ISSUE THREAD

**Issue by tombisho** [transbioZI/dsMTLClient#1]
Hi, I am trying to run the demo code against the opal-demo server.

on running: `m1=ds.LS_Lasso(X, Y, lam=0.1, C=0, opts, datasources=datasources, nDigits=4)`

I get the following error:
` "[Client error: (400) Bad Request] Lexical error at line 755, column 60.  Encountered: \"D\" (68), after : \".\""`

My client has DSI = 1.3.0, DSOpal = 1.3.1, opalr = 3.0.1

Is it expected that the demo code should run, or have I done something wrong?

**Comment by tombisho** [comment]
This morning it seems to be working fine. Maybe there was an issue with the opal-demo server

**Comment by hank9cao** [comment]
Great. Thanks for testing!
