### ISSUE TITLE
Bad reference of arguments

### ISSUE THREAD

**Issue by ESCRI11** [transbioZI/dsMTLClient#2]
Dear Han,

There is a bug on the `ds.Lasso_CVInSite` function. The input arguments X and Y are not passed to the `ds.subsetSubjests` function.

https://github.com/transbioZI/dsMTLClient/blob/main/R/ds.Lasso.R#L525-L528
https://github.com/transbioZI/dsMTLClient/blob/main/R/ds.Lasso.R#L547-L550

**Comment by hank9cao** [comment]
Hi Xavier,

Thanks for the report. I am so sorry for the late reply. Do you have a use case to repeat the error?

Regards,
Hank

**Comment by hank9cao** [comment]
Hi Xavier,

I closed the issue temporarily.

Please let me know if you still have issues.

Regards,
Hank
